name: humandoing
favicon: null
layout_spectrum: 0.2074195216409862
typography_spectrum: 0.6548937007319182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#454b4d'
    - '#9ae7ef'
    - '#05090c'
    - '#00afbc'
    - '#b6a289'
  brandStrength: 0.7592447500210255
  lightness: 0.3125
  saturation: 0.7363261848222464
  rhythmicContrast: 0.7554608297068626
purpose: []
